import nextEslintPluginNext from '@next/eslint-plugin-next';
import nx from '@nx/eslint-plugin';
import baseConfig from '../../eslint.config.mjs';

export default [
  { plugins: { '@next/next': nextEslintPluginNext } },
  ...nx.configs['flat/react-typescript'],
  ...baseConfig,
  {
    // next-env.d.ts is generated by Next.js and intentionally uses a
    // triple-slash reference, so it is excluded from linting.
    ignores: ['.next/**/*', '**/out-tsc', 'next-env.d.ts'],
  },
];
